In [1]:
import numpy as np

# Membuat matriks 3x3 dengan nilai antara 2 hingga 10
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
import numpy as np

# Array input
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

# Menghitung gabungan (union) dua array
union_array = np.union1d(array1, array2)
print("Gabungan dua array:", union_array)


Gabungan dua array: [ 0 10 20 30 40 50 60 70 80]


In [14]:
import pandas as pd

# Memuat data dari file CSV
data = pd.read_csv('data_1.csv')

# Menampilkan 7 data pertama
print("7 Data Pertama:")
print(data.head(7))

# Menampilkan 4 data terakhir
print("\n4 Data Terakhir:")
print(data.tail(4))

# Mengurutkan data berdasarkan kolom 'mass' secara ascending
data_sorted = data.sort_values(by='mass', ascending=True)
print("\nData diurutkan berdasarkan mass:")
print(data_sorted)

# Menampilkan hanya kolom 'fruit_name', 'width', dan 'height'
print("\nKolom fruit_name, width, dan height:")
print(data[['fruit_name', 'width', 'height']])


7 Data Pertama:
   fruit_label fruit_name fruit_subtype  mass  width  height
0            1      Apple  Granny_smith   192    8.4     7.3
1            1      Apple  Granny_smith   180    8.6     6.8
2            1      Apple  Granny_smith   176    7.4     7.2
3            2   Mandarin      Mandarin    86    6.2     4.7
4            2   Mandarin      Mandarin    84    6.0     4.6
5            2   Mandarin      Mandarin    80    5.8     4.3
6            1      Apple      Braeburn   166    6.9     7.3

4 Data Terakhir:
   fruit_label fruit_name fruit_subtype  mass  width  height
4            2   Mandarin      Mandarin    84    6.0     4.6
5            2   Mandarin      Mandarin    80    5.8     4.3
6            1      Apple      Braeburn   166    6.9     7.3
7            1      Apple      Braeburn   172    7.1     7.6

Data diurutkan berdasarkan mass:
   fruit_label fruit_name fruit_subtype  mass  width  height
5            2   Mandarin      Mandarin    80    5.8     4.3
4            2   

In [7]:
import pandas as pd

# Data Kabupaten dan Populasi
kabupaten = ['Semarang', 'Kendal', 'Batang', 'Pekalongan', 'Pemalang', 'Tegal']
populasi = [450000, 176000, 160000, 74000, 210000, 189000]

# Membuat data series
data_series = pd.Series(populasi, index=kabupaten)
print("Data Series Kabupaten dan Populasi:")
print(data_series)

# Menampilkan data teratas dan terakhir
print("\nData Teratas:")
print(data_series.head(1))
print("\nData Terakhir:")
print(data_series.tail(1))

# Menampilkan data dengan index 1 sampai 3
print("\nData dengan index 1 sampai 3:")
print(data_series.iloc[1:4])

# Menampilkan data kabupaten
print("\nNama Kabupaten:")
print(data_series.index)

# Menampilkan populasi saja
print("\nPopulasi:")
print(data_series.values)


Data Series Kabupaten dan Populasi:
Semarang      450000
Kendal        176000
Batang        160000
Pekalongan     74000
Pemalang      210000
Tegal         189000
dtype: int64

Data Teratas:
Semarang    450000
dtype: int64

Data Terakhir:
Tegal    189000
dtype: int64

Data dengan index 1 sampai 3:
Kendal        176000
Batang        160000
Pekalongan     74000
dtype: int64

Nama Kabupaten:
Index(['Semarang', 'Kendal', 'Batang', 'Pekalongan', 'Pemalang', 'Tegal'], dtype='object')

Populasi:
[450000 176000 160000  74000 210000 189000]
